# docker-compose file for Apache Guacamole
# Author: Svet Paregov
# Date: 2023-10-06

version: '2.0'

networks:
  guacamole_net:
    driver: bridge

# Note: The images are only AMD64, so you cannot run on Raspberry Pi
services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      guacamole_net:
    restart: unless-stopped
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw

  postgres:
    container_name: postgres_guacamole
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChangePasswordBeforeRun123'
      POSTGRES_USER: guacamole_user
    image: postgres:15.2-alpine
    networks:
      guacamole_net:
    restart: unless-stopped
    volumes:
    - ./init:/docker-entrypoint-initdb.d:z
    - ./data:/var/lib/postgresql/data:Z

  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChangePasswordBeforeRun123'
      POSTGRES_USER: guacamole_user
    image: guacamole/guacamole
    links:
    - guacd
    networks:
      guacamole_net:
    ports:
    - 8090:8080/tcp
    restart: unless-stopped
